[arlo_label label='<h5>Address</h5>']
    [arlo_venue_address layout="string" items="line1" wrap="%s"]
    [arlo_venue_address layout="string" items="line2" wrap="<br>%s"]
    [arlo_venue_address layout="string" items="line3" wrap="<br>%s"]
    [arlo_venue_address layout="string" items="line4" wrap="<br>%s"]
    [arlo_venue_address layout="string" items="suburb,city" wrap="<br>%s"]
    [arlo_venue_address layout="string" items="state" wrap="%s"]
    [arlo_venue_address layout="string" items="post_code" wrap="%s"]
    [arlo_venue_address layout="string" items="country" wrap="<br>%s"]
[/arlo_label]

[arlo_venue_directions label='<h5>Directions</h5>']
[arlo_venue_parking label='<h5>Parking</h5>']
[arlo_venue_map height="400" width="520"]
[arlo_powered_by]
[arlo_venue_rich_snippet]