<ul class="arlo-codes">
	<li>[arlo_event_template_code]</li>
	<li>[arlo_event_template_name]</li>
	<li>[arlo_event_template_summary]</li>
	<li>[arlo_timezones]</li>
	<li>[arlo_event_list]</li>
	<li>
		<ul>
			<li>[arlo_event_list_item]</li>
			<li>
				<ul>
					<li>[arlo_event_code]</li>
				 	<li>[arlo_event_start_date]</li>
					<li>[arlo_event_end_date]</li>
					<li>[arlo_event_location]</li>
					<li>[arlo_event_session_description]</li>
					<li>[arlo_event_presenters]</li>
					<li>[arlo_event_offers]</li>
					<li>[arlo_event_registration]</li>
				</ul>
			</li>
			<li>[/arlo_event_list_item]</li>
		</ul>
	</li>	
	<li>[/arlo_event_list]</li>
	<li>[arlo_suggest_datelocation]</li>
	<li>[arlo_content_field_list_item]</li>
	<li>
		<ul>
			<li>[arlo_content_field_name]</li>
			<li>[arlo_content_field_text]</li>
		</ul>
	</li>
	<li>[/arlo_content_field_list_item]</li>
</ul>