
<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

	$arlo_event_name = Arlo_For_Wordpress::$post_types['event']['singular_name'];

	// output the widget title
	$title = apply_filters( 'widget_title', empty( $instance['title'] ) ? $arlo_event_name . ' ' . __( 'Categories', 'arlo-training-and-event-management-system' ) : $instance['title'], $instance, $this->id_base );
	echo $before_title . esc_html($title) . $after_title; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Widget title output. $title is escaped, $before_title and $after_title are trusted widget arguments.

	// number of levels to display, "0" displays the full tree
	$arlo_depth = isset($instance['depth']) ? $instance['depth'] : 0 ;

	$arlo_parent = ($instance['parent']) ? '' : ' parent="0"';

	$arlo_shortcode = '[arlo_categories' . $arlo_parent . ' depth="' . $arlo_depth . '" widget="true"]';

	$arlo_output = do_shortcode($arlo_shortcode);

	if (!empty($arlo_output)) {
		$arlo_output = '<div class="arlo-categories-widget">' . $arlo_output . '</div>';	
	} else {
		$arlo_output = '<p>' . esc_html__('No categories to display.', 'arlo-training-and-event-management-system') . '</p>';
	} 

	// output the events list
	echo $arlo_output; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Categories list HTML output. Content is generated by shortcode and is safe.

	
